---

- name: Set port that postgres listens on
  lineinfile:
    path: "/etc/postgresql/{{ pg_major_version }}/main/postgresql.conf"
    regexp: '^[#\s]?port[ ]?='
    line: "port = {{ database_port }}"
  notify: 'restart postgres'

- name: Open listener to network interface
  lineinfile:
    path: "/etc/postgresql/{{ pg_major_version }}/main/postgresql.conf"
    regexp: '^[#\s]?listen_addresses[ ]?='
    line: "listen_addresses = 'localhost,{{ ansible_default_ipv4.address }}'"
  notify: 'restart postgres'

- name: Allow conns from network subnet
  lineinfile:
    path: "/etc/postgresql/{{ pg_major_version }}/main/pg_hba.conf"
    insertafter: '^#[ ]?IPv4 local connections'
    line: "host    all             all             {{ ansible_default_ipv4.network }}/24        scram-sha-256"
    state: present
  notify: 'restart postgres'

...
