---

- name: Install PyEnv dependencies
  apt:
    name: "{{ package }}"
    state: present
  loop_control:
    loop_var: 'package'
  loop:
    - 'make' 
    - 'build-essential'
    - 'libssl-dev'
    - 'zlib1g-dev'
    - 'libbz2-dev' 
    - 'libreadline-dev'
    - 'libsqlite3-dev'
    - 'curl'
    - 'git'
    - 'libncursesw5-dev' 
    - 'xz-utils'
    - 'tk-dev'
    - 'libxml2-dev'
    - 'libxmlsec1-dev'
    - 'libffi-dev' 
    - 'liblzma-dev'

- name: Get PyEnv
  shell:
    cmd: |
      curl https://pyenv.run | bash
  environment:
    PYENV_ROOT: "{{ pyenv_root }}"
  args:
    creates: "{{ pyenv_root }}"

- name: Add PyEnv aliases on .bashrc and .profile for root
  lineinfile:
    path: "{{ item.0 }}"
    line: "{{ item.1 }}"
  loop:
    - [ '/root/.bashrc', 'export PYENV_ROOT="{{ pyenv_root }}"']
    - [ '/root/.bashrc', '[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"']
    - [ '/root/.bashrc', 'eval "$(pyenv init - bash)"']
    - [ '/root/.profile', 'export PYENV_ROOT="{{ pyenv_root }}"']
    - [ '/root/.profile', '[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"']
    - [ '/root/.profile', 'eval "$(pyenv init - bash)"']

- name: Update PyEnv
  shell:
    cmd: |
      source /root/.bashrc && pyenv update
  args:
    executable: '/bin/bash'

- name: Install Python {{ app_python_version }}
  async: 3600
  poll: 20
  shell:
    cmd: |
      source /root/.bashrc && pyenv install {{ app_python_version }}
  args:
    executable: '/bin/bash'
    creates: "{{ pyenv_root }}/versions/{{ app_python_version }}"

- name: Link Python {{ app_python_version }} to /usr/local/bin
  file:
    src: "{{ pyenv_root }}/versions/{{ app_python_version }}/bin/python3"
    dest: "/usr/local/bin/python{{ app_python_version }}"
    owner: root
    group: root
    state: link

...
