---

- name: Load dataset vars
  include_vars:
    file: dataset-releases.yml

- name: Copy producer datasets
  copy:
    src: "{{ role_path }}/files/enriched_datasets/{{ release_year }}_peak_enriched.csv"
    dest: "{{ producer_base }}/data/{{ release_year }}_peak_enriched.csv"
    owner: kproducer
    group: kproducer
  loop: "{{ dataset_releases['dynamic'] | list }}"
  loop_control:
    loop_var: 'release_year'
    label: "{{ release_year }}_peak_enriched.csv"

...
