---

pyenv_root: "/usr/local/pyenv"

app_git_url: 'https://github.com/nksegos/unipi-ais.git'

app_python_version: '3.7.17'

app_python_dependencies:
  - 'wheel'
  - 'bokeh==2.3.0'
  - 'pandas==1.0.5'
  - 'numpy==1.18.5'
  - 'psycopg2==2.8.5'
  - 'geopandas==0.8.0'
  - 'requests==2.24.0'
  - 'beautifulsoup4==4.9.3'
  - 'tqdm==4.43.0'
  - 'jinja2==3.0.0'
  - 'confluent-kafka'
  - 'redis'
  - 'pyproj'

consumer_base: '/opt/kconsumer'

redis_host: 'localhost'
redis_port: 6379
redis_db: 0

...
