---

- hosts: "{{ groups['consumer'] | default([]) }}"
  become: yes
  gather_facts: yes
  pre_tasks:

    - name: Check that role is either 'omni' or 'consumer'
      include_role:
        name: common
        tasks_from: role-check.yml
      vars:
        target_role: 'consumer'
        strict_check: true

  tasks:

    - name: Start application services
      include_role:
        name: consumer
        tasks_from: start-application-services.yml

...
